#!/usr/bin/env bash
# Switch this machine to work profile: default github.com uses work key.
# Revert: rm ~/.ssh/config.local
#
# For additional internal hosts (e.g. company Git server), edit ~/.ssh/config.local
# manually after running this script — do not commit internal hostnames to this repo.
set -euo pipefail

LOCAL_CONFIG="$HOME/.ssh/config.local"
WORK_KEY="$HOME/.ssh/work_ed25519"

if [ ! -f "$WORK_KEY" ]; then
  echo "Error: work key not found at $WORK_KEY" >&2
  echo "Copy the key into place first, then re-run." >&2
  exit 1
fi

if [ -f "$LOCAL_CONFIG" ]; then
  echo "$LOCAL_CONFIG already exists."
  read -r -p "Overwrite? [y/N] " ans
  case "$ans" in
    [yY]|[yY][eE][sS]) : ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

cat > "$LOCAL_CONFIG" <<'EOF'
# Generated by ssh/work-profile.sh — work profile.
# Delete this file to revert to personal default.
# Add internal/company-specific Host blocks below as needed (not tracked in git).

Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/work_ed25519
    IdentitiesOnly yes
EOF

chmod 600 "$LOCAL_CONFIG"
echo "Work profile enabled. github.com now uses work key."
echo "Revert: rm $LOCAL_CONFIG"
